title: "Dokumentasi Pekerjaan Enggar Irawan"
description: "Catatan pekerjaan dan proyek sebagai Network Engineer"
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-paginate
  - jekyll-include-cache
  - jekyll-redirect-from
  - jekyll-mentions
  - jekyll-optional-front-matter
  - jekyll-titles-from-headings
  - jekyll-emoji