title: "Dokumentasi Pekerjaan Enggar Irawan"
description: "Catatan teknis & proyek"
baseurl: "/mve"   # ganti kalau repo path berbeda; kosong jika di user.github.io root
url: "https://ern-sys.github.io"
theme: minima
