site_name: Dokumentasi Kerja
theme:
  name: material
  palette:
    - scheme: default
      primary: teal
      accent: pink
    - scheme: slate
      primary: teal
      accent: pink
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
nav:
  - Home: index.md
  - Jaringan: jaringan.md
  - Server: server.md
  - Proxmox: proxmox.md
